branches: [ dev, qa, master ]
pipeline:
  install:
    image: node:8.1.2
    commands:
      - npm install --global yarn
      - yarn install
  check-git-logs:
    image: plugins/git
    commands:
      - git log -5 > git-logs.txt
      - cat git-logs.txt
      - rm git-logs.txt
  print-drone-vars:
    image: node:8.1.2
    commands:
      - yarn drone-vars
  unit-test:
    image: node:8.1.2
    commands:
      - yarn test
  integration-test-prepare:
    parallel: false
    prepare:
      image: plugins/git
      commands:
        - git branch -D MERGED_STATE || true
        - git fetch origin pull/$CI_PULL_REQUEST/head:MERGED_STATE
        - git checkout MERGED_STATE
        - git log -2
    test:
      image: node:8.1.2
      commands:
        - yarn test