branches: [ dev, qa, master ]
pipeline:
  install:
    image: node:8.1.2
    commands:
      - npm install --global yarn
      - yarn install
  print-drone-vars:
    image: node:8.1.2
    commands:
      - yarn drone-vars
  unit-test:
    image: node:8.1.2
    commands:
      - yarn test
  integration-test:
    image: git
    commands:
      - git fetch origin $BRANCH_NAME